### ISSUE TITLE
Support for PATCH in save

### ISSUE THREAD

**Issue by aweathe** [eosnewmedia/JSON-API-Client#2]
Hey Team, I'm attempting to implement this library and am having trouble with the fact that it doesn't seem to support `PATCH` for updating records. 

As per the JsonAPI documentation, updates should be done via a `PATCH` request and not a `POST`.
See [http://jsonapi.org/format/#crud-updating](http://jsonapi.org/format/#crud-updating)

Here's what I mean.

[vendor/enm/json-api-client/src/JsonApiClient.php](https://github.com/eosnewmedia/JSON-API-Client/blob/master/src/JsonApiClient.php)
```
    public function save(SaveRequestInterface $request): DocumentInterface
    {
        $uri = $this->buildUri($this->buildPath($request));
        return $this->handleResponse(
            $this->httpClient()->post(
                $uri,
                $this->buildRequestContent($request->document()),
                $request->headers()->all()
            )
        );
    }
```

When using Guzzle, this generates a `POST` request for update or create - which fails on our API.

I'n not sure if this is an issue with the code or a documentation issue?

Here's the implementation code (Note this also fails without setting the Content Type manually).
```
$resource = $this->getApiClient()->resource($this->getDefaultResource(), $id);
$resource->attributes()->set('global_tracked_status', $status);

$request = $this->getApiClient()->createSaveSingleResourceRequest($resource, true);
$request->headers()->set('Content-Type', 'application/json');

$result = $this->getApiClient()->save($request);
```
Obviously this can be fixed with something *like* the following, but this would probably be a breaking change without refactoring save entirely.

```
$method = $request->containsId() ? 'patch' : 'post';
return $this->handleResponse(
    $this->httpClient()->$method(
        $uri,
        $this->buildRequestContent($request->document()),
        $request->headers()->all()
    )
);
```

Thoughts?

**Comment by pmarien** [comment]
Hi @aaronweatherall,
you're right! I have fixed this issue.
To support POST requests with client generated id's I have added a new optional parameter "forceCreate".
The new tag is 1.2.0
