### ISSUE TITLE
Filtering Support

### ISSUE THREAD

**Issue by Snaver** [eosnewmedia/JSON-API-Client#3]
Hi There

In enm\json-api-common\src\Model\Request\FetchRequest.php I can see that there are properties for adding the 'filter' param to the API requests (private $filter;) but I can't see how I can set these outside of the class??

I guess it's similar to the 'include' functionality, which it seems can be utilised using `$request->include('myRelationship');`

Have I missed something or is this still WIP? :)

Thanks!

**Comment by Snaver** [comment]
This seemed to do the trick 😅

```
/**
 * Add filter parameter
 *
 * @param string $key
 * @param mixed $value
 * @return FetchRequestInterface
 */
public function addFilter(string $key, $value): FetchRequestInterface
{
    $this->filter->set($key, $value);

    return $this;
}
```

**Comment by pmarien** [comment]
In the new version (3.0.0) it will be $request->addFilter('yourFilter', 'yourFilterValue');

**Comment by pmarien** [comment]
Thanks, I have merged the feature, even if it was not necessary in my view, since it worked so far: $request->filter()->set($key, $value)
